# Generated by Django 2.2.6 on 2020-09-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='copy_counte',
            new_name='copy_count',
        ),
    ]
