# Generated by Django 2.2.6 on 2020-09-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200925_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.PublishingHouse', verbose_name='Издательство'),
        ),
    ]
