# Generated by Django 2.2.6 on 2020-09-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200916_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='copy_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
