# Generated by Django 2.2.6 on 2020-10-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200925_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='p_library.Author', verbose_name='Вербос_нэйм'),
        ),
    ]
