# Generated by Django 2.2.6 on 2020-09-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_book_copy_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='copy_count',
        ),
    ]
