# Generated by Django 2.2.6 on 2020-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20201013_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', through='p_library.Inspiration', to='p_library.Author'),
        ),
    ]
