# Generated by Django 2.2.6 on 2020-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0015_auto_20201022_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/%M/%S'),
        ),
        migrations.AlterField(
            model_name='author',
            name='face',
            field=models.ImageField(blank=True, upload_to='face_author/%M/%S'),
        ),
    ]
