# Generated by Django 2.2.6 on 2020-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0016_auto_20201023_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/%M/%S', verbose_name='Загрузить обложку'),
        ),
    ]
